-- MySQL Script generated by MySQL Workbench
-- Sun May  7 13:17:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Use this to set up correct database

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema userbase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userbase` DEFAULT CHARACTER SET utf8mb3 ;
USE `userbase` ;

-- -----------------------------------------------------
-- Table `userbase`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userbase`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `userbase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userbase`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `firstName` VARCHAR(20) NULL DEFAULT NULL,
  `lastName` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `userbase`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userbase`.`users_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `user_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `role_fk_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `userbase`.`roles` (`role_id`),
  CONSTRAINT `user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `userbase`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
